---
- name: Get Packetbeat
  get_url:
    url={{ elastic_download }}/downloads/beats/packetbeat/packetbeat-{{ elastic_version }}-amd64.deb
    dest=/opt/packetbeat.deb

- name: Install Packetbeat
  apt: deb=/opt/packetbeat.deb

- name: Create configuration file
  template:
    src: templates/{{ packetbeat_config_name }}.yml.j2
    dest: /etc/packetbeat/packetbeat.yml
    owner: root
    group: root
  notify:
    - restart packetbeat

- name: Start and enable packetbeat
  service: name=packetbeat state=started enabled=yes

- name: Import Packetbeat example dashboards
  command: /usr/share/{{ item }}/scripts/import_dashboards -es http://{{ elastic_host }}:{{ elastic_port }}
  with_items:
    - packetbeat
